# Variables
# BOOSTRAP
# export BOOSTRAP=51.83.75.29

version: '3.6'

services:

# -------------=== signer node ===-------------
  signernode:
    image: ghcr.io/jffp113/signernode
    container_name: signernode-1
    expose:
      - 8080
      - 9000
    ports:
      - "8080:8080"
      - "46431:46431"
    command: ./main --peerport=46431 -k ./resources/keys/1/ -b /ip4/${BOOTSTRAP}/tcp/55000/p2p/12D3KooWD1yUy23iVGYCYMZdm2fUy65WFaAc2H2i7ycBT3oJdN1B -vv

# -------------=== crypto ===-------------
  crypto:
    image: ghcr.io/jffp113/crypto
    container_name: crypto-1
    command: bash -c "sleep 3; ./main -u tcp://signernode:9000"
    depends_on:
      - signernode

# -------------=== smartcontract ===-------------
  smartcontract:
    image: ghcr.io/jffp113/sawtooth-smartcontract
    container_name: smartcontract-1
    command: intkey-tp-go -vv -C tcp://signernode:4004 -s TBLS256Optimistic
    depends_on:
      - signernode