#This Docker compose file describes a set of signer nodes in permissioned mode,
#each connected to its subcomponents, more specifically the Crypto Provider and the Smart Contract.
#The Smart-Contract is specified to return TBLS256 with n = 5 and t=3 when a transaction is requested to be validated by the Smart-Contract.
#Since this is a permissioned environment, the keys are already set up under the ./resources/keys folder

version: '3.6'

services:

# -------------=== bootstrap node ===-------------

  bootstrap:
    image: ghcr.io/jffp113/signernode
    container_name: bootstrap
    expose:
      - 55000
    ports:
      - "55000:55000"
    environment:
      - IS_BOOTSTRAP=true
    command: ./main

# -------------=== signer node ===-------------
  signernode-1:
    image: ghcr.io/jffp113/signernode
    container_name: signernode-1
    expose:
      - 8080
      - 9000
    ports:
      - "8080:8080"
      - "46431:46431"
    command: ./main --peerport=46431 -k ./resources/keys/1/ -b /dns4/bootstrap/tcp/55000/p2p/12D3KooWD1yUy23iVGYCYMZdm2fUy65WFaAc2H2i7ycBT3oJdN1B -vv
    depends_on:
      - bootstrap
  signernode-2:
    image: ghcr.io/jffp113/signernode
    container_name: signernode-2
    expose:
      - 8080
      - 9000
    ports:
      - "8081:8080"
      - "46432:46432"
    command: ./main --peerport=46432 -k ./resources/keys/2/ -b /dns4/bootstrap/tcp/55000/p2p/12D3KooWD1yUy23iVGYCYMZdm2fUy65WFaAc2H2i7ycBT3oJdN1B -vv
    depends_on:
      - bootstrap
  signernode-3:
    image: ghcr.io/jffp113/signernode
    container_name: signernode-3
    expose:
      - 8080
      - 9000
    ports:
      - "8082:8080"
      - "46433:46433"
    command: ./main --peerport=46433  -k ./resources/keys/3/ -b /dns4/bootstrap/tcp/55000/p2p/12D3KooWD1yUy23iVGYCYMZdm2fUy65WFaAc2H2i7ycBT3oJdN1B -vv
    depends_on:
      - bootstrap
  signernode-4:
    image: ghcr.io/jffp113/signernode
    container_name: signernode-4
    expose:
      - 8080
      - 9000
    ports:
      - "8083:8080"
      - "46434:46434"
    command: ./main --peerport=46434 -k ./resources/keys/4/ -b /dns4/bootstrap/tcp/55000/p2p/12D3KooWD1yUy23iVGYCYMZdm2fUy65WFaAc2H2i7ycBT3oJdN1B -vv
    depends_on:
      - bootstrap
  signernode-5:
    image: ghcr.io/jffp113/signernode
    container_name: signernode-5
    expose:
      - 8080
      - 9000
    ports:
      - "8084:8080"
      - "46435:46435"
    command: ./main --peerport=46435 -k ./resources/keys/5/ -b /dns4/bootstrap/tcp/55000/p2p/12D3KooWD1yUy23iVGYCYMZdm2fUy65WFaAc2H2i7ycBT3oJdN1B -vv
    depends_on:
      - bootstrap


# -------------=== crypto ===-------------
  crypto-1:
    image: ghcr.io/jffp113/crypto
    container_name: crypto-1
    command: bash -c "sleep 3; ./main -u tcp://signernode-1:9000"
    depends_on:
      - signernode-1
  crypto-2:
    image: ghcr.io/jffp113/crypto
    container_name: crypto-2
    command:  bash -c "sleep 3; ./main -u tcp://signernode-2:9000"
    depends_on:
      - signernode-2
  crypto-3:
    image: ghcr.io/jffp113/crypto
    container_name: crypto-3
    command:  bash -c "sleep 3; ./main -u tcp://signernode-3:9000"
    depends_on:
      - signernode-3
  crypto-4:
    image: ghcr.io/jffp113/crypto
    container_name: crypto-4
    command:  bash -c "sleep 3; ./main -u tcp://signernode-4:9000"
    depends_on:
      - signernode-4
  crypto-5:
    image: ghcr.io/jffp113/crypto
    container_name: crypto-5
    command:  bash -c "sleep 3; ./main -u tcp://signernode-5:9000"
    depends_on:
      - signernode-5

# -------------=== smartcontract ===-------------

  smartcontract-1:
    image: ghcr.io/jffp113/sawtooth-smartcontract
    container_name: smartcontract-1
    command: intkey-tp-go -vv -C tcp://signernode-1:4004 -s TBLS256Optimistic
    depends_on:
      - signernode-1
  smartcontract-2:
    image: ghcr.io/jffp113/sawtooth-smartcontract
    container_name: smartcontract-2
    command: intkey-tp-go -vv -C tcp://signernode-2:4004 -s TBLS256Optimistic
    depends_on:
      - signernode-2
  smartcontract-3:
    image: ghcr.io/jffp113/sawtooth-smartcontract
    container_name: smartcontract-3
    command: intkey-tp-go -vv -C tcp://signernode-3:4004 -s TBLS256Optimistic
    depends_on:
      - signernode-3
  smartcontract-4:
    image: ghcr.io/jffp113/sawtooth-smartcontract
    container_name: smartcontract-4
    command: intkey-tp-go -vv -C tcp://signernode-4:4004 -s TBLS256Optimistic
    depends_on:
      - signernode-4
  smartcontract-5:
    image: ghcr.io/jffp113/sawtooth-smartcontract
    container_name: smartcontract-5
    command: intkey-tp-go -vv -C tcp://signernode-5:4004 -s TBLS256Optimistic
    depends_on:
      - signernode-5

networks:
  default:
    external:
      name: networkThesis