# Copyright 2019 Cargill Incorporated
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: '3.6'

services:

# -------------=== bootstrap node ===-------------

  bootstrap:
    image: ghcr.io/jffp113/signernode
    container_name: bootstrap
    expose:
      - 55000
    ports:
      - "55000:55000"
    environment:
      - IS_BOOTSTRAP=true
    command: ./main

# -------------=== signer node ===-------------
  signernode-1:
    image: ghcr.io/jffp113/signernode
    container_name: signernode-1
    expose:
      - 8080
      - 9000
    ports:
      - "8080:8080"
      - "46431:46431"
    command: ./main --peerport=46431 -k ./resources/keys/1/ -b /dns4/bootstrap/tcp/55000/p2p/12D3KooWD1yUy23iVGYCYMZdm2fUy65WFaAc2H2i7ycBT3oJdN1B -vv
    depends_on:
      - bootstrap
  signernode-2:
    image: ghcr.io/jffp113/signernode
    container_name: signernode-2
    expose:
      - 8080
      - 9000
    ports:
      - "46432:46432"
    command: ./main --peerport=46432  -k ./resources/keys/2/ -b /dns4/bootstrap/tcp/55000/p2p/12D3KooWD1yUy23iVGYCYMZdm2fUy65WFaAc2H2i7ycBT3oJdN1B -vv
    depends_on:
      - bootstrap
  signernode-3:
    image: ghcr.io/jffp113/signernode
    container_name: signernode-3
    expose:
      - 8080
      - 9000
    ports:
      - "46433:46433"
    command: ./main --peerport=46433 -t Byzantine  -k ./resources/keys/3/ -b /dns4/bootstrap/tcp/55000/p2p/12D3KooWD1yUy23iVGYCYMZdm2fUy65WFaAc2H2i7ycBT3oJdN1B -vv
    depends_on:
      - bootstrap

# -------------=== crypto ===-------------
  crypto-1:
    image: ghcr.io/jffp113/crypto
    container_name: crypto-1
    command: bash -c "sleep 3; ./main -u tcp://signernode-1:9000"
    depends_on:
      - signernode-1
  crypto-2:
    image: ghcr.io/jffp113/crypto
    container_name: crypto-2
    command:  bash -c "sleep 3; ./main -u tcp://signernode-2:9000"
    depends_on:
      - signernode-2
  crypto-3:
    image: ghcr.io/jffp113/crypto
    container_name: crypto-3
    command:  bash -c "sleep 3; ./main -u tcp://signernode-3:9000"
    depends_on:
      - signernode-3

# -------------=== smartcontract ===-------------

  smartcontract-1:
    image: ghcr.io/jffp113/sawtooth-smartcontract
    container_name: smartcontract-1
    command: intkey-tp-go -vv -C tcp://signernode-1:4004 -s TBLS256Optimistic
    depends_on:
      - signernode-1
  smartcontract-2:
    image: ghcr.io/jffp113/sawtooth-smartcontract
    container_name: smartcontract-2
    command: intkey-tp-go -vv -C tcp://signernode-2:4004 -s TBLS256Optimistic
    depends_on:
      - signernode-2

networks:
  default:
    external:
      name: networkThesis